// ============================================================
// Nexus-Panel gRPC 服务定义 (简化版: 无 well-known types 依赖)
// 通信方向: node-agent(客户端) <-> panel(服务端)
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: nexus.proto

package nexuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户状态枚举
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_ACTIVE             UserStatus = 1
	UserStatus_USER_DISABLED           UserStatus = 2
	UserStatus_USER_EXPIRED            UserStatus = 3
	UserStatus_USER_TRAFFIC_EXHAUSTED  UserStatus = 4
	UserStatus_USER_LOCKED             UserStatus = 5
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_ACTIVE",
		2: "USER_DISABLED",
		3: "USER_EXPIRED",
		4: "USER_TRAFFIC_EXHAUSTED",
		5: "USER_LOCKED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_ACTIVE":             1,
		"USER_DISABLED":           2,
		"USER_EXPIRED":            3,
		"USER_TRAFFIC_EXHAUSTED":  4,
		"USER_LOCKED":             5,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

// 协议类型枚举
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_VMESS       Protocol = 1
	Protocol_PROTOCOL_VLESS       Protocol = 2
	Protocol_PROTOCOL_TROJAN      Protocol = 3
	Protocol_PROTOCOL_SHADOWSOCKS Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_VMESS",
		2: "PROTOCOL_VLESS",
		3: "PROTOCOL_TROJAN",
		4: "PROTOCOL_SHADOWSOCKS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_VMESS":       1,
		"PROTOCOL_VLESS":       2,
		"PROTOCOL_TROJAN":      3,
		"PROTOCOL_SHADOWSOCKS": 4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

// ============================================================
// 通用响应
// ============================================================
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// ============================================================
// 节点服务
// ============================================================
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode   string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Protocol      Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=nexus.Protocol" json:"protocol,omitempty"`
	ServerAddress string                 `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	ServerConfig  string                 `protobuf:"bytes,7,opt,name=server_config,json=serverConfig,proto3" json:"server_config,omitempty"` // JSON 字符串(含 REALITY 公钥等)
	TrafficLimit  int64                  `protobuf:"varint,8,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	TrafficUsed   int64                  `protobuf:"varint,9,opt,name=traffic_used,json=trafficUsed,proto3" json:"traffic_used,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	NodeToken     string                 `protobuf:"bytes,11,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,12,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Online        bool                   `protobuf:"varint,13,opt,name=online,proto3" json:"online,omitempty"`
	Version       string                 `protobuf:"bytes,14,opt,name=version,proto3" json:"version,omitempty"`
	LastSeenAt    int64                  `protobuf:"varint,15,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"` // unix 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *NodeInfo) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *NodeInfo) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetServerConfig() string {
	if x != nil {
		return x.ServerConfig
	}
	return ""
}

func (x *NodeInfo) GetTrafficLimit() int64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *NodeInfo) GetTrafficUsed() int64 {
	if x != nil {
		return x.TrafficUsed
	}
	return 0
}

func (x *NodeInfo) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *NodeInfo) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *NodeInfo) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *NodeInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeToken     string                 `protobuf:"bytes,1,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	ServerAddress string                 `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *RegisterRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Node          *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *RegisterResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeToken         string                 `protobuf:"bytes,10,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CpuUsage          float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal       int64                  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	OnlineConnections int32                  `protobuf:"varint,6,opt,name=online_connections,json=onlineConnections,proto3" json:"online_connections,omitempty"`
	UptimeSeconds     float64                `protobuf:"fixed64,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TrafficLimit      int64                  `protobuf:"varint,8,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	TrafficUsed       int64                  `protobuf:"varint,9,opt,name=traffic_used,json=trafficUsed,proto3" json:"traffic_used,omitempty"`
	// 修复 NODE-HEALTH-01: agent REALITY 自检结果上报, 区分 agent 进程可达 vs 代理服务可用
	ProxyReachable    bool                   `protobuf:"varint,11,opt,name=proxy_reachable,json=proxyReachable,proto3" json:"proxy_reachable,omitempty"`
	ProxyLatencyMs    int64                  `protobuf:"varint,12,opt,name=proxy_latency_ms,json=proxyLatencyMs,proto3" json:"proxy_latency_ms,omitempty"`
	ProxyError        string                 `protobuf:"bytes,13,opt,name=proxy_error,json=proxyError,proto3" json:"proxy_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *HeartbeatRequest) GetOnlineConnections() int32 {
	if x != nil {
		return x.OnlineConnections
	}
	return 0
}

func (x *HeartbeatRequest) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetTrafficLimit() int64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *HeartbeatRequest) GetTrafficUsed() int64 {
	if x != nil {
		return x.TrafficUsed
	}
	return 0
}

// 修复 NODE-HEALTH-01: REALITY 自检结果 Getter
func (x *HeartbeatRequest) GetProxyReachable() bool {
	if x != nil {
		return x.ProxyReachable
	}
	return false
}

func (x *HeartbeatRequest) GetProxyLatencyMs() int64 {
	if x != nil {
		return x.ProxyLatencyMs
	}
	return 0
}

func (x *HeartbeatRequest) GetProxyError() string {
	if x != nil {
		return x.ProxyError
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	ConfigChanged bool                   `protobuf:"varint,2,opt,name=config_changed,json=configChanged,proto3" json:"config_changed,omitempty"`
	UsersChanged  bool                   `protobuf:"varint,3,opt,name=users_changed,json=usersChanged,proto3" json:"users_changed,omitempty"`
	ServerTime    int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *HeartbeatResponse) GetConfigChanged() bool {
	if x != nil {
		return x.ConfigChanged
	}
	return false
}

func (x *HeartbeatResponse) GetUsersChanged() bool {
	if x != nil {
		return x.UsersChanged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeToken     string                 `protobuf:"bytes,2,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetConfigRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *GetConfigRequest) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

type NodeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	XrayConfig    string                 `protobuf:"bytes,3,opt,name=xray_config,json=xrayConfig,proto3" json:"xray_config,omitempty"` // 完整 Xray 服务端配置 JSON
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`                               // 元信息 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfigResponse) Reset() {
	*x = NodeConfigResponse{}
	mi := &file_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfigResponse) ProtoMessage() {}

func (x *NodeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfigResponse.ProtoReflect.Descriptor instead.
func (*NodeConfigResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{7}
}

func (x *NodeConfigResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *NodeConfigResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *NodeConfigResponse) GetXrayConfig() string {
	if x != nil {
		return x.XrayConfig
	}
	return ""
}

func (x *NodeConfigResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type ReportStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeToken         string                 `protobuf:"bytes,6,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage          float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	OnlineConnections int32                  `protobuf:"varint,4,opt,name=online_connections,json=onlineConnections,proto3" json:"online_connections,omitempty"`
	UptimeSeconds     float64                `protobuf:"fixed64,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_nexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{8}
}

func (x *ReportStatusRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *ReportStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportStatusRequest) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ReportStatusRequest) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ReportStatusRequest) GetOnlineConnections() int32 {
	if x != nil {
		return x.OnlineConnections
	}
	return 0
}

func (x *ReportStatusRequest) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// ============================================================
// 流量服务
// ============================================================
type TrafficRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UploadBytes   int64                  `protobuf:"varint,3,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes int64                  `protobuf:"varint,4,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	LogTime       int64                  `protobuf:"varint,5,opt,name=log_time,json=logTime,proto3" json:"log_time,omitempty"` // unix 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRecord) Reset() {
	*x = TrafficRecord{}
	mi := &file_nexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRecord) ProtoMessage() {}

func (x *TrafficRecord) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRecord.ProtoReflect.Descriptor instead.
func (*TrafficRecord) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{9}
}

func (x *TrafficRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrafficRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TrafficRecord) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *TrafficRecord) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *TrafficRecord) GetLogTime() int64 {
	if x != nil {
		return x.LogTime
	}
	return 0
}

type ReportRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeToken     string                 `protobuf:"bytes,3,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Records       []*TrafficRecord       `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRealtimeRequest) Reset() {
	*x = ReportRealtimeRequest{}
	mi := &file_nexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRealtimeRequest) ProtoMessage() {}

func (x *ReportRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRealtimeRequest.ProtoReflect.Descriptor instead.
func (*ReportRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{10}
}

func (x *ReportRealtimeRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *ReportRealtimeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportRealtimeRequest) GetRecords() []*TrafficRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ReportRealtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRealtimeResponse) Reset() {
	*x = ReportRealtimeResponse{}
	mi := &file_nexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRealtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRealtimeResponse) ProtoMessage() {}

func (x *ReportRealtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRealtimeResponse.ProtoReflect.Descriptor instead.
func (*ReportRealtimeResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{11}
}

func (x *ReportRealtimeResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *ReportRealtimeResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type UserTrafficSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalUsed     int64                  `protobuf:"varint,2,opt,name=total_used,json=totalUsed,proto3" json:"total_used,omitempty"`
	TrafficLimit  int64                  `protobuf:"varint,3,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	Status        UserStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=nexus.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTrafficSummary) Reset() {
	*x = UserTrafficSummary{}
	mi := &file_nexus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTrafficSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrafficSummary) ProtoMessage() {}

func (x *UserTrafficSummary) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrafficSummary.ProtoReflect.Descriptor instead.
func (*UserTrafficSummary) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{12}
}

func (x *UserTrafficSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTrafficSummary) GetTotalUsed() int64 {
	if x != nil {
		return x.TotalUsed
	}
	return 0
}

func (x *UserTrafficSummary) GetTrafficLimit() int64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *UserTrafficSummary) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type QueryUserTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeToken     string                 `protobuf:"bytes,2,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserTrafficRequest) Reset() {
	*x = QueryUserTrafficRequest{}
	mi := &file_nexus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserTrafficRequest) ProtoMessage() {}

func (x *QueryUserTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserTrafficRequest.ProtoReflect.Descriptor instead.
func (*QueryUserTrafficRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{13}
}

func (x *QueryUserTrafficRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *QueryUserTrafficRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *QueryUserTrafficRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type QueryUserTrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Users         []*UserTrafficSummary  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserTrafficResponse) Reset() {
	*x = QueryUserTrafficResponse{}
	mi := &file_nexus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserTrafficResponse) ProtoMessage() {}

func (x *QueryUserTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserTrafficResponse.ProtoReflect.Descriptor instead.
func (*QueryUserTrafficResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{14}
}

func (x *QueryUserTrafficResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *QueryUserTrafficResponse) GetUsers() []*UserTrafficSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

// ============================================================
// 用户同步服务
// ============================================================
type UserCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`         // VMess/VLESS UUID
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // Trojan/SS 密码
	TrafficLimit  int64                  `protobuf:"varint,5,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	TrafficUsed   int64                  `protobuf:"varint,6,opt,name=traffic_used,json=trafficUsed,proto3" json:"traffic_used,omitempty"`
	Status        UserStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=nexus.UserStatus" json:"status,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,8,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // unix 时间戳, 0=不限
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCredential) Reset() {
	*x = UserCredential{}
	mi := &file_nexus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCredential) ProtoMessage() {}

func (x *UserCredential) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCredential.ProtoReflect.Descriptor instead.
func (*UserCredential) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{15}
}

func (x *UserCredential) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCredential) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserCredential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCredential) GetTrafficLimit() int64 {
	if x != nil {
		return x.TrafficLimit
	}
	return 0
}

func (x *UserCredential) GetTrafficUsed() int64 {
	if x != nil {
		return x.TrafficUsed
	}
	return 0
}

func (x *UserCredential) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserCredential) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *UserCredential) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeToken     string                 `protobuf:"bytes,2,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	SinceVersion  int64                  `protobuf:"varint,3,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"` // 0=全量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUsersRequest) Reset() {
	*x = SyncUsersRequest{}
	mi := &file_nexus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUsersRequest) ProtoMessage() {}

func (x *SyncUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUsersRequest.ProtoReflect.Descriptor instead.
func (*SyncUsersRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{16}
}

func (x *SyncUsersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncUsersRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *SyncUsersRequest) GetSinceVersion() int64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

type SyncUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Users         []*UserCredential      `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	LatestVersion int64                  `protobuf:"varint,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUsersResponse) Reset() {
	*x = SyncUsersResponse{}
	mi := &file_nexus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUsersResponse) ProtoMessage() {}

func (x *SyncUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUsersResponse.ProtoReflect.Descriptor instead.
func (*SyncUsersResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{17}
}

func (x *SyncUsersResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SyncUsersResponse) GetUsers() []*UserCredential {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SyncUsersResponse) GetLatestVersion() int64 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

var File_nexus_proto protoreflect.FileDescriptor

const file_nexus_proto_rawDesc = "" +
	"\n" +
	"\vnexus.proto\x12\x05nexus\"L\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\xd5\x03\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12+\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x0f.nexus.ProtocolR\bprotocol\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12#\n" +
	"\rserver_config\x18\a \x01(\tR\fserverConfig\x12#\n" +
	"\rtraffic_limit\x18\b \x01(\x03R\ftrafficLimit\x12!\n" +
	"\ftraffic_used\x18\t \x01(\x03R\vtrafficUsed\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\n" +
	" \x01(\bR\tisEnabled\x12\x1d\n" +
	"\n" +
	"node_token\x18\v \x01(\tR\tnodeToken\x12\x1b\n" +
	"\tgrpc_port\x18\f \x01(\x05R\bgrpcPort\x12\x16\n" +
	"\x06online\x18\r \x01(\bR\x06online\x12\x18\n" +
	"\aversion\x18\x0e \x01(\tR\aversion\x12 \n" +
	"\flast_seen_at\x18\x0f \x01(\x03R\n" +
	"lastSeenAt\"\xaa\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"node_token\x18\x01 \x01(\tR\tnodeToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\x05R\bgrpcPort\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\"\\\n" +
	"\x10RegisterResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12#\n" +
	"\x04node\x18\x02 \x01(\v2\x0f.nexus.NodeInfoR\x04node\"\xe5\x02\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"node_token\x18\n" +
	" \x01(\tR\tnodeToken\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x03R\vmemoryTotal\x12-\n" +
	"\x12online_connections\x18\x06 \x01(\x05R\x11onlineConnections\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x01R\ruptimeSeconds\x12#\n" +
	"\rtraffic_limit\x18\b \x01(\x03R\ftrafficLimit\x12!\n" +
	"\ftraffic_used\x18\t \x01(\x03R\vtrafficUsed\"\xa5\x01\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12%\n" +
	"\x0econfig_changed\x18\x02 \x01(\bR\rconfigChanged\x12#\n" +
	"\rusers_changed\x18\x03 \x01(\bR\fusersChanged\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"q\n" +
	"\x10GetConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_token\x18\x02 \x01(\tR\tnodeToken\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\"\x95\x01\n" +
	"\x12NodeConfigResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vxray_config\x18\x03 \x01(\tR\n" +
	"xrayConfig\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\"\xe3\x01\n" +
	"\x13ReportStatusRequest\x12\x1d\n" +
	"\n" +
	"node_token\x18\x06 \x01(\tR\tnodeToken\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12-\n" +
	"\x12online_connections\x18\x04 \x01(\x05R\x11onlineConnections\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x01R\ruptimeSeconds\"\xa6\x01\n" +
	"\rTrafficRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fupload_bytes\x18\x03 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x04 \x01(\x03R\rdownloadBytes\x12\x19\n" +
	"\blog_time\x18\x05 \x01(\x03R\alogTime\"\x7f\n" +
	"\x15ReportRealtimeRequest\x12\x1d\n" +
	"\n" +
	"node_token\x18\x03 \x01(\tR\tnodeToken\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\arecords\x18\x02 \x03(\v2\x14.nexus.TrafficRecordR\arecords\"Y\n" +
	"\x16ReportRealtimeResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\"\x9c\x01\n" +
	"\x12UserTrafficSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"total_used\x18\x02 \x01(\x03R\ttotalUsed\x12#\n" +
	"\rtraffic_limit\x18\x03 \x01(\x03R\ftrafficLimit\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.nexus.UserStatusR\x06status\"l\n" +
	"\x17QueryUserTrafficRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_token\x18\x02 \x01(\tR\tnodeToken\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\tR\auserIds\"p\n" +
	"\x18QueryUserTrafficResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.nexus.UserTrafficSummaryR\x05users\"\xa1\x02\n" +
	"\x0eUserCredential\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12#\n" +
	"\rtraffic_limit\x18\x05 \x01(\x03R\ftrafficLimit\x12!\n" +
	"\ftraffic_used\x18\x06 \x01(\x03R\vtrafficUsed\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.nexus.UserStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expired_at\x18\b \x01(\x03R\texpiredAt\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"o\n" +
	"\x10SyncUsersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_token\x18\x02 \x01(\tR\tnodeToken\x12#\n" +
	"\rsince_version\x18\x03 \x01(\x03R\fsinceVersion\"\x8c\x01\n" +
	"\x11SyncUsersResponse\x12#\n" +
	"\x04resp\x18\x01 \x01(\v2\x0f.nexus.ResponseR\x04resp\x12+\n" +
	"\x05users\x18\x02 \x03(\v2\x15.nexus.UserCredentialR\x05users\x12%\n" +
	"\x0elatest_version\x18\x03 \x01(\x03R\rlatestVersion*\x8c\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vUSER_ACTIVE\x10\x01\x12\x11\n" +
	"\rUSER_DISABLED\x10\x02\x12\x10\n" +
	"\fUSER_EXPIRED\x10\x03\x12\x1a\n" +
	"\x16USER_TRAFFIC_EXHAUSTED\x10\x04\x12\x0f\n" +
	"\vUSER_LOCKED\x10\x05*{\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePROTOCOL_VMESS\x10\x01\x12\x12\n" +
	"\x0ePROTOCOL_VLESS\x10\x02\x12\x13\n" +
	"\x0fPROTOCOL_TROJAN\x10\x03\x12\x18\n" +
	"\x14PROTOCOL_SHADOWSOCKS\x10\x042\x88\x02\n" +
	"\vNodeService\x12;\n" +
	"\bRegister\x12\x16.nexus.RegisterRequest\x1a\x17.nexus.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.nexus.HeartbeatRequest\x1a\x18.nexus.HeartbeatResponse\x12?\n" +
	"\tGetConfig\x12\x17.nexus.GetConfigRequest\x1a\x19.nexus.NodeConfigResponse\x12;\n" +
	"\fReportStatus\x12\x1a.nexus.ReportStatusRequest\x1a\x0f.nexus.Response2\xb4\x01\n" +
	"\x0eTrafficService\x12M\n" +
	"\x0eReportRealtime\x12\x1c.nexus.ReportRealtimeRequest\x1a\x1d.nexus.ReportRealtimeResponse\x12S\n" +
	"\x10QueryUserTraffic\x12\x1e.nexus.QueryUserTrafficRequest\x1a\x1f.nexus.QueryUserTrafficResponse2Q\n" +
	"\x0fUserSyncService\x12>\n" +
	"\tSyncUsers\x12\x17.nexus.SyncUsersRequest\x1a\x18.nexus.SyncUsersResponseB\x1bZ\x19nexus-panel/proto;nexuspbb\x06proto3"

var (
	file_nexus_proto_rawDescOnce sync.Once
	file_nexus_proto_rawDescData []byte
)

func file_nexus_proto_rawDescGZIP() []byte {
	file_nexus_proto_rawDescOnce.Do(func() {
		file_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)))
	})
	return file_nexus_proto_rawDescData
}

var file_nexus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_nexus_proto_goTypes = []any{
	(UserStatus)(0),                  // 0: nexus.UserStatus
	(Protocol)(0),                    // 1: nexus.Protocol
	(*Response)(nil),                 // 2: nexus.Response
	(*NodeInfo)(nil),                 // 3: nexus.NodeInfo
	(*RegisterRequest)(nil),          // 4: nexus.RegisterRequest
	(*RegisterResponse)(nil),         // 5: nexus.RegisterResponse
	(*HeartbeatRequest)(nil),         // 6: nexus.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 7: nexus.HeartbeatResponse
	(*GetConfigRequest)(nil),         // 8: nexus.GetConfigRequest
	(*NodeConfigResponse)(nil),       // 9: nexus.NodeConfigResponse
	(*ReportStatusRequest)(nil),      // 10: nexus.ReportStatusRequest
	(*TrafficRecord)(nil),            // 11: nexus.TrafficRecord
	(*ReportRealtimeRequest)(nil),    // 12: nexus.ReportRealtimeRequest
	(*ReportRealtimeResponse)(nil),   // 13: nexus.ReportRealtimeResponse
	(*UserTrafficSummary)(nil),       // 14: nexus.UserTrafficSummary
	(*QueryUserTrafficRequest)(nil),  // 15: nexus.QueryUserTrafficRequest
	(*QueryUserTrafficResponse)(nil), // 16: nexus.QueryUserTrafficResponse
	(*UserCredential)(nil),           // 17: nexus.UserCredential
	(*SyncUsersRequest)(nil),         // 18: nexus.SyncUsersRequest
	(*SyncUsersResponse)(nil),        // 19: nexus.SyncUsersResponse
}
var file_nexus_proto_depIdxs = []int32{
	1,  // 0: nexus.NodeInfo.protocol:type_name -> nexus.Protocol
	2,  // 1: nexus.RegisterResponse.resp:type_name -> nexus.Response
	3,  // 2: nexus.RegisterResponse.node:type_name -> nexus.NodeInfo
	2,  // 3: nexus.HeartbeatResponse.resp:type_name -> nexus.Response
	2,  // 4: nexus.NodeConfigResponse.resp:type_name -> nexus.Response
	11, // 5: nexus.ReportRealtimeRequest.records:type_name -> nexus.TrafficRecord
	2,  // 6: nexus.ReportRealtimeResponse.resp:type_name -> nexus.Response
	0,  // 7: nexus.UserTrafficSummary.status:type_name -> nexus.UserStatus
	2,  // 8: nexus.QueryUserTrafficResponse.resp:type_name -> nexus.Response
	14, // 9: nexus.QueryUserTrafficResponse.users:type_name -> nexus.UserTrafficSummary
	0,  // 10: nexus.UserCredential.status:type_name -> nexus.UserStatus
	2,  // 11: nexus.SyncUsersResponse.resp:type_name -> nexus.Response
	17, // 12: nexus.SyncUsersResponse.users:type_name -> nexus.UserCredential
	4,  // 13: nexus.NodeService.Register:input_type -> nexus.RegisterRequest
	6,  // 14: nexus.NodeService.Heartbeat:input_type -> nexus.HeartbeatRequest
	8,  // 15: nexus.NodeService.GetConfig:input_type -> nexus.GetConfigRequest
	10, // 16: nexus.NodeService.ReportStatus:input_type -> nexus.ReportStatusRequest
	12, // 17: nexus.TrafficService.ReportRealtime:input_type -> nexus.ReportRealtimeRequest
	15, // 18: nexus.TrafficService.QueryUserTraffic:input_type -> nexus.QueryUserTrafficRequest
	18, // 19: nexus.UserSyncService.SyncUsers:input_type -> nexus.SyncUsersRequest
	5,  // 20: nexus.NodeService.Register:output_type -> nexus.RegisterResponse
	7,  // 21: nexus.NodeService.Heartbeat:output_type -> nexus.HeartbeatResponse
	9,  // 22: nexus.NodeService.GetConfig:output_type -> nexus.NodeConfigResponse
	2,  // 23: nexus.NodeService.ReportStatus:output_type -> nexus.Response
	13, // 24: nexus.TrafficService.ReportRealtime:output_type -> nexus.ReportRealtimeResponse
	16, // 25: nexus.TrafficService.QueryUserTraffic:output_type -> nexus.QueryUserTrafficResponse
	19, // 26: nexus.UserSyncService.SyncUsers:output_type -> nexus.SyncUsersResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_nexus_proto_init() }
func file_nexus_proto_init() {
	if File_nexus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_nexus_proto_goTypes,
		DependencyIndexes: file_nexus_proto_depIdxs,
		EnumInfos:         file_nexus_proto_enumTypes,
		MessageInfos:      file_nexus_proto_msgTypes,
	}.Build()
	File_nexus_proto = out.File
	file_nexus_proto_goTypes = nil
	file_nexus_proto_depIdxs = nil
}
